#!/usr/bin/env bash

export LD_PRELOAD=$cc_ld_preload
export LD_LIBRARY_PATH=$cc_ld_library_path

echo "

Output :
---------------------------------------------------"

case "$1" in
debug)
    tmux switch-client -t amos
    tmux setenv LD_PRELOAD "$LD_PRELOAD" \; setenv LD_LIBRARY_PATH "$LD_LIBRARY_PATH" \; run -t amos 'tmuxgdb deb'
    ;;
debug_test)
    tmux switch-client -t amos
    tmux setenv LD_PRELOAD "$LD_PRELOAD" \; setenv LD_LIBRARY_PATH "$LD_LIBRARY_PATH" \; run -t amos 'tmuxgdb deb_test'
    ;;
bench)
    ./bench --benchmark_color=false
    ;;
test)
    ./rel_test
    ;;
*)
    ./rel
    ;;
esac
